// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace XedoTests.Features.HomePage
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("HomePageOptions", SourceFile="Features\\HomePage\\HomePageOptions.feature", SourceLine=0)]
    public partial class HomePageOptionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HomePageOptions.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HomePageOptions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I am on the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The Let\'s Get Started button should take me to the collections page", SourceLine=5)]
        public virtual void TheLetSGetStartedButtonShouldTakeMeToTheCollectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Let\'s Get Started button should take me to the collections page", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 7
 testRunner.When("I click the home page banner lets-get-started button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("I should be taken to the collections page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The Perfect Match Get Started button should take me to the collections page", SourceLine=9)]
        public virtual void ThePerfectMatchGetStartedButtonShouldTakeMeToTheCollectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Perfect Match Get Started button should take me to the collections page", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 11
 testRunner.When("I click the perfect match get-started button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("I should be taken to the collections page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The How It Works Get Started button should take me to the collections page", SourceLine=13)]
        public virtual void TheHowItWorksGetStartedButtonShouldTakeMeToTheCollectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The How It Works Get Started button should take me to the collections page", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 15
 testRunner.When("I click the how it works get-started button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("I should be taken to the collections page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails(string index, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The collections should create a popup displaying the correct details", exampleTags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 19
 testRunner.When(string.Format("I click the home page collection at index {0}", index), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("a product details popup should appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("the product details should display the correct image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("the product details should display the correct name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("the product details should display the correct price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 0", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_0()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("0", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 1", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_1()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 2", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_2()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("2", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 3", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_3()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 4", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_4()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("4", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 5", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_5()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("5", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 6", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_6()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("6", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 7", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_7()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("7", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 8", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_8()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("8", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 9", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_9()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("9", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 10", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_10()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("10", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 11", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_11()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("11", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 12", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_12()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("12", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 13", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_13()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("13", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 14", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_14()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("14", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 15", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_15()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("15", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 16", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_16()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("16", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The collections should create a popup displaying the correct details, 17", SourceLine=26)]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails_17()
        {
            this.TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails("17", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("HomePageOptions")]
    public partial class HomePageOptionsFeature_NUnit
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "HomePageOptions.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "HomePageOptions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line 4
 testRunner.Given("I am on the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Let\'s Get Started button should take me to the collections page")]
        public virtual void TheLetSGetStartedButtonShouldTakeMeToTheCollectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Let\'s Get Started button should take me to the collections page", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 7
 testRunner.When("I click the home page banner lets-get-started button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 8
 testRunner.Then("I should be taken to the collections page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The Perfect Match Get Started button should take me to the collections page")]
        public virtual void ThePerfectMatchGetStartedButtonShouldTakeMeToTheCollectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The Perfect Match Get Started button should take me to the collections page", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 11
 testRunner.When("I click the perfect match get-started button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("I should be taken to the collections page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The How It Works Get Started button should take me to the collections page")]
        public virtual void TheHowItWorksGetStartedButtonShouldTakeMeToTheCollectionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The How It Works Get Started button should take me to the collections page", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 15
 testRunner.When("I click the how it works get-started button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("I should be taken to the collections page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The collections should create a popup displaying the correct details")]
        [NUnit.Framework.TestCaseAttribute("0", new string[0])]
        [NUnit.Framework.TestCaseAttribute("1", new string[0])]
        [NUnit.Framework.TestCaseAttribute("2", new string[0])]
        [NUnit.Framework.TestCaseAttribute("3", new string[0])]
        [NUnit.Framework.TestCaseAttribute("4", new string[0])]
        [NUnit.Framework.TestCaseAttribute("5", new string[0])]
        [NUnit.Framework.TestCaseAttribute("6", new string[0])]
        [NUnit.Framework.TestCaseAttribute("7", new string[0])]
        [NUnit.Framework.TestCaseAttribute("8", new string[0])]
        [NUnit.Framework.TestCaseAttribute("9", new string[0])]
        [NUnit.Framework.TestCaseAttribute("10", new string[0])]
        [NUnit.Framework.TestCaseAttribute("11", new string[0])]
        [NUnit.Framework.TestCaseAttribute("12", new string[0])]
        [NUnit.Framework.TestCaseAttribute("13", new string[0])]
        [NUnit.Framework.TestCaseAttribute("14", new string[0])]
        [NUnit.Framework.TestCaseAttribute("15", new string[0])]
        [NUnit.Framework.TestCaseAttribute("16", new string[0])]
        [NUnit.Framework.TestCaseAttribute("17", new string[0])]
        public virtual void TheCollectionsShouldCreateAPopupDisplayingTheCorrectDetails(string index, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The collections should create a popup displaying the correct details", exampleTags);
#line 18
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 19
 testRunner.When(string.Format("I click the home page collection at index {0}", index), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 20
 testRunner.Then("a product details popup should appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 21
 testRunner.And("the product details should display the correct image", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("the product details should display the correct name", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.And("the product details should display the correct price", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
